name: shopkeeper_shop
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^8.0.2
  intl: ^0.20.2
  provider: ^6.1.5+1
  share_plus: ^12.0.1
  supabase_flutter: ^2.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/Gemini_Generated_Image_rdbuu1rdbuu1rdbu.png"
  min_sdk_android: 21
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/Gemini_Generated_Image_rdbuu1rdbuu1rdbu.png"

